version: '3.8'

services:
  # Backend API Service (Development)
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: cornfield-todo-api-dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - ./server:/app
      - node_modules_server:/app/node_modules
    command: npm run dev
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - cornfield-network

  # Frontend React Service (Development)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: cornfield-todo-frontend-dev
    ports:
      - "3000:3000"
    depends_on:
      server:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - node_modules_client:/app/node_modules
    command: npm start
    restart: unless-stopped
    networks:
      - cornfield-network

# Networks
networks:
  cornfield-network:
    driver: bridge
    name: cornfield-todo-network-dev

# Volumes
volumes:
  node_modules_server:
  node_modules_client:
